music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :sessions, only: [:create, :new, :destroy]
  resources :users, only: [:create, :new, :show]
  resources :bands do
    resources :albums, only: [:new]
  end
  resources :albums, except: [:new, :index] do
    resource :tracks, only: [:new]
  end
  resources :tracks, except: [:new, :index]
end

music_app/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  band_id    :integer          not null
#  year       :integer          not null
#  live       :boolean          default(FALSE), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ApplicationRecord
  validates :band_id, :title, :year, presence: true

  belongs_to :band
  has_many :tracks
end

music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

music_app/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums
end

music_app/app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  ord        :integer          not null
#  lyrics     :text
#  album_id   :integer          not null
#  bonus      :boolean          default(FALSE), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Track < ApplicationRecord
  validates :title, :ord, :album_id, :bonus, presence: true

  belongs_to :album

end

music_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :email, :session_token, presence: true, uniqueness: true
  validates :password, length: { minimum: 6 }, allow_nil: true
  validates :password_digest, presence: true

  attr_reader :password

  after_initialize :ensure_session_token

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil unless user && user.is_password?(password)
    user
  end

  def reset_session_token!
    self.update!(session_token: User.generate_session_token)
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end


end

music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  
  def new
    @album = Album.new
    render :new
  end

  def create
    # params[:album][:live] = Boolean.new.cast(params[:album][:live]) if ["true","false"].include?(params[:ablum][:live])
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_url(@album.id)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def update
    @album = Album.find(params[:id])
    if @album.update_attributes(album_params)
      redirect_to album_url(@album.id)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])
    band_id = @album.band_id
    @album.destroy
    redirect_to band_url(band_id)
  end

  private

  def album_params
    params.require(:album).permit(:title, :year, :live, :band_id)
  end

end

music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def login(user)
    session[:session_token] = user.reset_session_token!
    @current_user = user
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
    @current_user = nil
  end

end

music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
    render :index
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band.id)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def update
    @band = Band.find(params[:id])
    if @band.update_attributes(band_params)
      redirect_to band_url(@band.id)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end

end

music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # LOGIN
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(user_params[:email], user_params[:password])
    if @user
      login(@user)
      redirect_to user_url(@user) #no need for the .id on @user
    else
      flash.now[:errors] = ["Invalid email password combo"]
      @user = User.new(email: params[:user][:email])
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_sessions_url
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end

end

music_app/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  
  def new

    @track = Track.new
    render :new
  end

  def create
    # debugger
    @track = Track.new(track_params)
    if @track.save
      redirect_to track_url(@track.id)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :new
    end
  end

  def edit
    @track = Track.find(params[:id])
    render :edit
  end

  def show
    @track = Track.find(params[:id])
    render :show
  end

  def update
    @track = Track.find(params[:id])
    if @track.update_attributes(track_params)
      redirect_to album_url(@track.id)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :edit
    end
  end

  def destroy
    @track = Track.find(params[:id])
    album_id = @track.album_id
    @track.destroy
    redirect_to album_url(album_id)
  end

  private

  def track_params
    params.require(:track).permit(:title, :year, :live, :album_id, :lyrics)
  end

end

music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to user_url(@user.id)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end

end

music_app/app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
      "<input
          type=\"hidden\"
          name=\"authenticity_token\"
          value=\"#{form_authenticity_token}\"
          />".html_safe
  end

end

music_app/app/views/albums/edit.html.erb
<h1>Edit Album</h1>

<form action="<%=album_url(@album.id)%>" method="POST">
  <input type="hidden" name="_method" value="PATCH">
  <%= auth_token %>
  <label>Title: <input type="text" name="album[title]" value="<%=@album.title%>"></label>
  <br>
  <label>Year: <input type="number" name="album[year]" min="1" max="2500" value="<%=@album.year%>"></label>
  <br>
  <label>
    Band: 
    <select name="album[band_id]" id="bands">
    <% Band.all.each do |band| %>
      <option
        <%= @album.band_id == band.id ? "selected" : "" %>
        value="<%= band.id %>">
        <%= band.name %>
      </option>
    <% end %>
  </select>
  </label>
  <br>
  <input
    type="radio"
    name="album[live]"
    value="false"
    id="studio_album"
    <%= @album[:live] == false ? "checked" : "" %>>
  <label for="cat_sex_male">Studio</label>
  <input
    type="radio"
    name="album[live]"
    value="true"
    id="live_album"
    <%= @album[:live] == true ? "checked" : "" %>>
  <label for="cat_sex_female">Live</label>
  <br>
  <input type="submit" value="Edit Album">
</form>

music_app/app/views/albums/new.html.erb
<h1>New Album</h1>

<form action="<%=albums_url%>" method="POST">
  <%= auth_token %>
  <label>Title: <input type="text" name="album[title]" value="<%=@album.title%>"></label>
  <br>
  <label>Year: <input type="number" name="album[year]" min="1" max="2500" value="<%=@album.year%>"></label>
  <br>
  <label>
    Band: 
    <select name="album[band_id]" id="bands">
    <% Band.all.each do |band| %>
      <option
        <%= params[:band_id] == band.id.to_s ? "selected" : "" %>
        value="<%= band.id %>">
        <%= band.name %>
      </option>
    <% end %>
  </select>
  </label>
  <br>
  <input
    type="radio"
    name="album[live]"
    value="false"
    id="studio_album"
    <%= @album[:live] == false ? "checked" : "" %>>
  <label for="cat_sex_male">Studio</label>
  <input
    type="radio"
    name="album[live]"
    value="true"
    id="live_album"
    <%= @album[:live] == true ? "checked" : "" %>>
  <label for="cat_sex_female">Live</label>
  <br>
  <input type="submit" value="Create Album">
</form>

music_app/app/views/albums/show.html.erb
<h1>Show Single Album</h1>

<h3><%=@album.title%></h3>

<a href="<%=edit_album_url(@album.id)%>">Edit Album</a>
<br>
<a href="<%=band_url(@album.band_id)%>">Back to Band</a>


<br>
<br>
<br>

<form action="<%=album_url(@album.id)%>" method="POST">
  <%= auth_token %>
  <input type="hidden" name="_method" value="DELETE">
  <input type="submit" value="Delete Album">
</form>

<a href="<%=new_album_tracks_url(@album.id)%>">Create Track</a>

<% if @album.tracks %>
  <ul>
    <% @album.tracks.each do |track| %>
      <li><%=track.title%></li>
      <a href="<%=edit_track_url(track.id)%>">Edit Track</a>
    <% end %>
  </ul>
<% end %>

music_app/app/views/bands/edit.html.erb
<h1>Edit Band</h1>

<form action="<%=band_url(@band.id)%>" method="POST">
  <input type="hidden" name="_method" value="PATCH">
  <%= auth_token %>
  <label>Name of Band: <input type="text" name="band[name]" value="<%=@band.name%>"></label>
  <br>
  <input type="submit" value="Update Band!">
</form>

music_app/app/views/bands/index.html.erb
<h1>All Bands</h1>


<% if @bands %>
  <ul>
    <% @bands.each do |band| %>
      <li><%=band.name%></li>
      <a href="<%=band_url(band.id)%>">Show Band</a>
      <a href="<%=edit_band_url(band.id)%>">Edit Band</a>
    <% end %>
  </ul>
<% end %>

<a href="<%=new_band_url%>">New Band</a>

music_app/app/views/bands/new.html.erb
<h1>New Band</h1>

<form action="<%=bands_url%>" method="POST">
  <%= auth_token %>
  <label>Name of Band: <input type="text" name="band[name]" value="<%=@band.name%>"></label>
  <br>
  <input type="submit" value="Create Band">
</form>

music_app/app/views/bands/show.html.erb
<h1>One Band</h1>

<h3><%=@band.name%></h3>
<a href="<%=edit_band_url(@band.id)%>">Edit Band</a>
<a href="<%=bands_url%>">All Bands</a>
<br>
<br>
<br>
<a href="<%= new_band_album_url(@band.id) %>">Create New Album</a>

<h3>Albums:</h3>


<% if @band.albums %>
  <ul>
    <% @band.albums.each do |album| %>
      <li><%=album.title%></li>
      <a href="<%=album_url(album.id)%>">Album Page</a>
    <% end %>
  </ul>
<% end %>

music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1 class="title_text">Welcome to this AMAZING Music App</h1>
    <p class="title_sub_text">Support our GoFundMe at: venmo[@dan_keinan]</p>
    <% if logged_in? %>
      <a href="<%=user_url(current_user)%>">Back to Profile</a>
      <form action="<%=sessions_url%>" method="POST" class="logout_form">
        <%= auth_token %>
        <input type="hidden" name="_method" value="DELETE">
        <input type="submit" value="Log Out">
      </form>

    <% else %>
      <div class="logup_nav">
        <a href="<%=new_sessions_url%>">Login</a>
        <a href="<%=new_user_url%>">Sign Up</a>
      </div>
    <% end %>

    
    <% if flash[:errors] %>
      <ul>
        <% flash[:errors].each do |error| %>
          <li><%=error%></li>
        <% end %>
      </ul>
    <% end %>
    
    
    <%= yield %>

  </body>
</html>

music_app/app/views/tracks/new.html.erb
<h1>New Track</h1>

<form action="<%=tracks_url%>" method="POST">
  <%= auth_token %>
  <label>Title: <input type="text" name="track[title]" value="<%=@track.title%>"></label>
  <br>
  <label>Ord: <input type="number" name="track[ord]" min="1" value="<%=@track.ord%>"></label>
  <br>
  <label>
    Album: 
    <select name="track[album_id]" id="albums">
    <% Album.where(band_id: Album.find(params[:album_id]).band_id).each do |album| %>
      <option
        <%= params[:album_id] == album.id.to_s ? "selected" : "" %>
        value="<%= album.id %>">
        <%= album.title %>
      </option>
    <% end %>
  </select>
  </label>
  <br>
  <input
    type="radio"
    name="track[bonus]"
    value="false"
    id="track_bonus"
    <%= @track[:bonus] == false ? "checked" : "" %>>
  <label for="track_bonus">Regular</label>
  <input
    type="radio"
    name="track[bonus]"
    value="true"
    id="track_bonus"
    <%= @track[:bonus] == true ? "checked" : "" %>>
  <label for="track_bonus">Bonus</label>
  <br>

  <label>Lyrics: 
    <textarea name="track[lyrics]" value="<%=@track.lyrics%>"></textarea>
  </label>
  <br>
  <input type="submit" value="Create Track">
</form>

music_app/app/views/users/new.html.erb
<h3 class="title_sub_text">Sign Up Page</h3>

<form action="<%=users_url%>" method="POST" class="email_pass_form">
  <%= auth_token %>
  <label>Email: <input type="text" name="user[email]" value="<%=@user.email%>"></label>
  <br>
  <label>Password: <input type="text" name="user[password]" value=""></label>
  <br>
  <input type="submit" value="Sign Up">
</form>

music_app/app/views/users/show.html.erb
<h1><%=@user.email%></h1>

<a href="<%=bands_url%>">All Bands</a>